version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: security_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: security_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-boot-network

volumes:
  mysql-data:

networks:
  spring-boot-network:
    driver: bridge